# Generated by Django 4.0.4 on 2022-04-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
