# Generated by Django 4.0.4 on 2022-05-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
